directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: com.e-school-cambodia.com
productName: E-SCHOOL
publish:
  provider: github
  owner: channvuthy271
  token: <stripped sensitive data>
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
  icon: build/icons/icon.ico
electronVersion: 7.3.3
