directories:
  output: dist_electron
  buildResources: build
  app: dist_electron/bundled
files:
  - filter:
      - '**'
extends: null
appId: com.e-school-cambodia.com
productName: E-SCHOOL
copyright: Copyright ©2021 E-School Cambodia
publish:
  provider: github
  owner: channvuthy271
  host: github.com
  protocol: https
  releaseType: release
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
  icon: build/icons/icon.ico
linux:
  target: deb
mac:
  target:
    - dmg
    - zip
    - pkg
  category: education
  icon: build/icons/icon.icns
dmg:
  sign: false
electronVersion: 7.3.3
